name: keyconfig CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Lint All
        uses: Jerome1337/golint-action@v1.0.2
        with:
          golint-path: './...'