name: keyconfig CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Lint All
        uses: Jerome1337/golint-action@v1.0.2
        with:
          golint-path: './...'

  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '^1.17.3'
      - name: Test All
        run: go test -v ./...